language: python
cache: pip
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # this allows 'v1.2.3' like tags to be build
sudo: false
matrix:    
    fast_finish: true
    include:
        - python: 3.7
          env: TOXENV=py37
        - python: 3.7
          env: TOXENV=docs
services:
  - xvfb
before_install:
  - git remote set-branches origin master && git fetch
  # avoid "no display name and no $DISPLAY environment variable"
  - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install: 
  - pip install tox tox-venv
script: 
  - tox -e $TOXENV
